### ISSUE TITLE
Feature Request: Keyboard

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#10]
Could you enable Keyboard to be managed in the same way as other controller devices ?

Thanks in advance
stuart

**Comment by EthanTuning** [comment]
I would second this motion. The keyboard keys do not get recorded when you try to bind them to a specific relation.

**Comment by Holdi601** [comment]
Mhh I could think about it, that said keyboard *should* already be supported in modifiers

**Comment by speed-of-heat** [comment]
Modifiers are supported, but I have no way of exporting them from DCS.

If I want to remap “show pilot” to “Y” or whatever, Keyboard is not exportable as a separate device ?

Thanks STuar t

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by EthanTuning** [comment]
I agree, this would make the setup of all controls a lot cleaner and easier.

**Comment by Holdi601** [comment]
I can look into this, once i have the features im working on rn done i.e. IL2 implementation

**Comment by speed-of-heat** [comment]
Fair enough, many thanks!

Thanks,
Stuart

Get Outlook<https://aka.ms/sdimjr> for iOS
________________________________

**Comment by Holdi601** [comment]
first implementation should be in next version @speed-of-heat

**Comment by speed-of-heat** [comment]
woot :)
