### ISSUE TITLE
Cage/Uncage not working in-game

### ISSUE THREAD

**Issue by EthanTuning** [Holdi601/JoystickProfiler#11]
This may not have anything to do with JoyPro. 

However, I used JoyPro to setup all my controls. I did not set a bind for CAGE/UNCAGE, since I like it to stay the default "C" keyboard key. I finished by selecting "Clean Existing Binds and Export" with "Keep Defaults" checked. 

I then hopped into the F/A-18C to do some maverick practice and realized that CAGE/UNCAGE default Key was not working. It would not actually perform the action. I looked at my controls in-game and the "C" was in-fact still set as the bind.

Is it possible that JoyPro is somehow causing default controls to have issues after setting things up?

**Comment by Holdi601** [comment]
JoyPro does only change at the current point things for joystick, it is not touching anything keyboard (unless its a modifier) and also just the stuff that is in Saved games.  Also im not touching the default luas itself, im reading them, but im not altering them.

I mean i don't know exactly how DCS works under the hood, but the creation of joystick keybinds should not interfere with keyboard keybinds. Do you have red exclamanation marks in DCS in the F18?

**Comment by EthanTuning** [comment]
Interesting, no. I have no red exclamations. 

Yeah I am not sure, but seems to be very strange behavior that a simple, default keyboard keybind would not work anymore. It would seem very strange if it was in fact your program that caused this, but it is the only variable I isolated when troubleshooting this problem.

**Comment by Holdi601** [comment]
If so go into you saved games\DCS\Config\Input\FA-18C_hornet\joystick and delete everything in there, does the C button start to work again?

**Comment by EthanTuning** [comment]
Yes actually, okay, interesting. I then re-setup controls with JoyPro and everything seems to be working.

**Comment by Holdi601** [comment]
Interesting first time i hear about this, but certainly not the first weird issue im facing :D

**Comment by EthanTuning** [comment]
Haha the nature of the beast. I am also a software engineer, so I understand your pain!
