### ISSUE TITLE
Feature Request: Search and Filter 

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#15]
would it be possible to add a search/and or filter to be able to filter out specific devices or to search for specific buttons or axis

**Comment by Holdi601** [comment]
Do you mean on the overview? (Right now you have sort options by clicking on the captions)

**Comment by speed-of-heat** [comment]
Yes I found those and it sort of helps, but, it doesn’t remove the screen “noise”, it’s sometimes quite difficult to “see” the exact item you want. I have close on 200 relations and I’m not even finished yet, so it’s quite noisy.  It would be very useful to filter on type.. just axis for example or button … with 6 devices I have a lot of button 1 - 40 in use, or even relation name.

**Comment by Holdi601** [comment]
comes with v0040
