### ISSUE TITLE
Feature Request: UI improvements adding to a relation/clicking

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#16]
Not sure if it is just me, but, it takes me between 3/4 mouse clicks to unclick a relation… when it adds them automatically for every aircraft that can be a lot of clicks!

Could you check if there is already a relation selected in the column, and if so not default it to checked when you add to an existing relation?

Also would it be possible to use cursor keys for navigation between the check boxes?

**Comment by Holdi601** [comment]
I can't completely follow here, do you mean here in the general overview, or do you mean in the Create/edit relation window?

**Comment by speed-of-heat** [comment]
yes sorry, that  correct, when adding a new or editing an existing relation

**Comment by Holdi601** [comment]
should be fixed in v40
