### ISSUE TITLE
Instance is not being saved 

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#17]
Every time i go into to JoyPro the instance is not being saved on the current build? and i have to reselect ?

**Comment by Holdi601** [comment]
Yeah the logic changed in the background. Now it just remembers the last thing you have worked on as in the profile. And when it opens it it knows these are DCS relations you have worked on (So for future if there are multiple games and you have relations over multiple games, that the program gets in the right state automatically) So the last selected instance thing is something i have to rebuild at some other place or include in the profile.

**Comment by Holdi601** [comment]
should be fixed in v0040
