### ISSUE TITLE
Custom Commands not being imported from UI Layer

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#18]
I can's seem to get the following binds imported in from the UI Layer:

JOY_BTN85 | VR Spyglass Zoom IN | VR | d2605pnilunilcdnilvd1vpnilvunil
-- | -- | -- | --
  | VR Spyglass Zoom OUT | VR | d2605pnilunilcdnilvd0vpnilvunil
JOY_BTN84 | VR Zoom IN | VR | d2604pnilunilcdnilvd1vpnilvunil
JOY_BTN86 | VR Zoom OUT | VR | d2604pnilunilcdnilvd0vpnilvunil

I have exported them to html and i have the instance correctly set?

[Thrustmaster Combined {35C3A630-EA83-11e8-8004-444553540000}.zip](https://github.com/Holdi601/JoystickProfiler/files/6413910/Thrustmaster.Combined.35C3A630-EA83-11e8-8004-444553540000.zip)

**Comment by Holdi601** [comment]
I will add those manually to the UI layer.

**Comment by Holdi601** [comment]
Okay either you wait for next release, or you manually download this file and overwrite the same file in the same location with this one https://github.com/Holdi601/JoystickProfiler/blob/master/JoyPro/JoyPro/DB/DCS/UiLayer.html 

Cheers.

**Comment by speed-of-heat** [comment]
Thanks!
