### ISSUE TITLE
JoyPro crashing when loading template file

### ISSUE THREAD

**Issue by PJHubbell** [Holdi601/JoystickProfiler#2]
I just grabbed the latest build, followed the directions on the YouTube video, as soon as I choose Load Relations, I get an app crashed error 
"The application has crashed and it will now be dismissed...."
[Exception_132602306019405119.zip](https://github.com/Holdi601/JoystickProfiler/files/6137616/Exception_132602306019405119.zip)

.NET, Python all updated to latest versions.

**Comment by Holdi601** [comment]
Have you tried redownloading the relation file and tried to open again? 
Had the other day a user with same error but his downloaded file went corrupt and caused this.
In the error i just see that it couldn't parse the relations file that it wasnt the right format

**Comment by PJHubbell** [comment]
Thanks, That seemed to work. Looks like the original one I downloaded first was 1/2 the size. Thanks again!
