### ISSUE TITLE
Does not correctly export to Thrustmaster combined

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#20]
for lots of complex reasons (mostly to create operating switches where there is only press and release) i use target scripting to combine my HOTAS WARTHOG Stick and Throttle .  It produces a device called Thrustmaster combined. 

When i export from JoyPro, it does not seem to bring in any of the buttons from the combined device... this is a showstopper for me. 

I should add it does import one axis ... 

What data files do you need to help diagnose what's going on ?

**Comment by speed-of-heat** [comment]
Here are the profiles, and before and after config input folders; if you need anything else let me know
[Input after and backup.zip](https://github.com/Holdi601/JoystickProfiler/files/6414869/Input.after.and.backup.zip)
[JoyPro.zip](https://github.com/Holdi601/JoystickProfiler/files/6414873/JoyPro.zip)

**Comment by Holdi601** [comment]
So what exactly is the issue? Right now the issue sounds to me:
You want to bind an axis, you click on bind, but it does not bind the correct axis to it?

**Comment by speed-of-heat** [comment]
it seems to work in Joypro, but when export from Joypro there is literally only one axis (despite several buttons and axis being mapped as relations in joypro) , and no buttons actually mapped in DCS, every other device exports just fine (and is maddeningly good)  but i can't use it to map buttons or axis on the combined device.

**Comment by Holdi601** [comment]
Mhh for quicker turnaround in communication could you join the discord for troubleshooting purposes? Right now i have the profile open and it looks good im trying to export but i can only theoretically go over if something goes wrong

if you map something in DCS to the combined one could you upload a .diff.lua of the combined stick of how that looks like so i can compare both data structures to each other?
