### ISSUE TITLE
Duplicate relations ID 

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#21]
![Joypro](https://user-images.githubusercontent.com/64099136/117042975-8bb06600-ad04-11eb-8056-c5d1e450e8d9.png)
Any idea how to get rid of the duplicate names ?

**Comment by Holdi601** [comment]
Mhh i mean the titles are duplicates but the hashes are not, So it might be a different function inside DCS

**Comment by speed-of-heat** [comment]
My original problem was that a button mapping, wasn't showing up at all (for these ID's the rest worked fine), I was pulling my hair out, but when i looked in the diff.lua, I found the buttons were present, but, when I imported  the binding back into Joypro from DCS they would disappear in joypro. 

I then exported the DCS mappings to HTML to compare them and found that the same function STORES SELECT n and PCA SELECT n, both had different ID's in the Joypro DB.  

The "correct" ID's are the shorter ones, that one comes from the export to HTML from the mirage, the longer one seems to be from the joypro database file for the mirage 2000, the shorter ID's are recognised by DCS.

**Comment by Holdi601** [comment]
Ah interesting, so the IDs have changed or my Mirage have different hashIDs other than yours. Thats weird but if the latter is the case idk what to do about it, as both is needed depending on the mirage installation

**Comment by speed-of-heat** [comment]
right, so the question is this isolated or can it happen elsewhere....

if it does happen else where we need a way of editing out the old ones from the DB/overriding them. The problem here is of course we end up with a bunch of variations that need to be saved and maintained and updated etc...

**Comment by Holdi601** [comment]
Thing is, if it happens that the ID changed due to an update, how can JP know it did?

For updating or adding new IDs to the database that's less of an issue i thought of building in a feature if it doesn't know the ID that it adds it to the DB, if there is something in the saved profile, or in the imported diff lua or in the html files.

But the other way around might be problematic to detect.

**Comment by speed-of-heat** [comment]
yeah , thats why i think it needs to be a human driven UI if you accommodate it at all...

**Comment by Holdi601** [comment]
yeah but how would that look like? If i push a new version, i always push the build of my database, so if manually edit something in yours, the changes would get overwritten as soon as a new version drops.
If i change that so you would maintain your first download Database, then for instance if i include like the Mi-24 in the next update, you wouldn't get it until you generated an HTML on your end. 

The only somewhat viable thing in that regards if you do manual changes to the DB, that is changes them as a difference and when you use the next version that it can look up the differences you have previously made.

**Comment by speed-of-heat** [comment]
I was think more of a separate diff db for each user that they are responsible for maintaining 

if aircraft + description has more than one ID  throw UI , Keep, Choose -> write to local diff db

have a menu option to revert one or more changes, if it no longer works, or force behaviour

**Comment by Holdi601** [comment]
I will add it to my feature request list

**Comment by Holdi601** [comment]
I have added my todo list to the front readme file , so people can see what is on the list.
