### ISSUE TITLE
Multiple relations to same bind will only export last one

### ISSUE THREAD

**Issue by pavel-slama** [Holdi601/JoystickProfiler#22]
Hi,
my use case is to have multiple axes on same controller bound to single DCS axis.

Example: Spitfire
Using either of toe brakes to control common single brake axis.

DCS allows you to bind multiple "combos" - axes or buttons to same action even if on the same controller.

But when I create the relations accordingly in Joypro - it will complain on Validate Profile but mainly - seems to export only the last binding per controller.

It should correctly export all bindings from multiple relations as multiple combos.
[multiple-combos.zip](https://github.com/Holdi601/JoystickProfiler/files/6448582/multiple-combos.zip)

Pedals Axis X -> Wheel Brake (single axis)
Pedals Axis Y -> Wheel Brake (single axis)
But only Y axis gets exported.

**Comment by speed-of-heat** [comment]
Have you tried creating a separate profile, for the secondary access and buttons? And then do a profile merge, rather then than a clean? I suggest this as a temporary workaround…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Pavel Slama ***@***.***>
Sent: Sunday, May 9, 2021 11:57:58 PM
To: Holdi601/JoystickProfiler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Holdi601/JoystickProfiler] Multiple relations to same bind will only export last one (#22)


Hi,
my use case is to have multiple controllers or multiple axes on same controllerbound to single DCS axis.

Example: Spitfire
Using either of toe brakes to control common single brake axis.

DCS allows you to bind multiple "combos" - axes or buttons to same action even if on the same controller.

But when I create the relations accordingly in Joypro - it will complain on Validate Profile but mainly only seems to exports last bind per controller.

It should correctly export all bindings from multiple relations as multiple combos.
multiple-combos.zip<https://github.com/Holdi601/JoystickProfiler/files/6448582/multiple-combos.zip>

**Comment by Holdi601** [comment]
I have not worked on multiple keys for the same id-plane item, as my assumption was and still is that most people are scarce of buttons and axis. But as @speed-of-heat pointed out, you might be able to achieve that with multiple exports and the merge. But that would be another feature request.

**Comment by speed-of-heat** [comment]
It is sometime useful to bind a button or an axis twice, thinking of buttons like the ka50 gear toggle, or break axis on the spitfire ...as examples

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pavel-slama** [comment]
There are more use cases:
Brake axis on any plane with differential braking (if your stick doesn't have a paddle axis).
Rudder trim on a standard buttons + on a roll trim buttons in case the plane doesn't have a roll trim.

But mainly DCS allows this - Joypro if aspiring to manage the config completely should handle that too.
Thanks for workaround suggestion though - I'll try today and let you know :)

**Comment by pavel-slama** [comment]
Got some results:

Profile with double-assigned axes and buttons

1. Merge and Overwrite
- exports only last assignment for over-assigned items

2. Merge, Keep Existing and Add to (same profile)
- adds over-assigned buttons, but not axes

Profile with missing axes assignments only
3. Merge, Keep Existing and Add to
- adds over-assigned axes

So I can do with 2 profiles, the second one containing only missing overloaded axis assignments. Cumbersome but works.
Thanks

**Comment by Holdi601** [comment]
Clean write should support now this or rather in next version from v57. Please reopen if that is not the case.
