### ISSUE TITLE
Minor UI Error on Set User Curve

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#23]
the seventh data entry box is smaller and not vertically cantered
![Joy Pro Format Error](https://user-images.githubusercontent.com/64099136/118164235-c5772000-b41a-11eb-9a1a-7fba8b7ed3f1.png)

**Comment by speed-of-heat** [comment]
Also could the UI at this point confirm which Curve you are editing , by showing the relation name ?

**Comment by Holdi601** [comment]
fixed in v0040
