### ISSUE TITLE
Bindings not showing once exported into DCS

### ISSUE THREAD

**Issue by PJHubbell** [Holdi601/JoystickProfiler#26]
After setting up the bindings for my X56 HOTAS, I removed all inputs from DCS openbeta input folder, then "Clean Existing Binds and Export"

I saw the folders get created (as shown below). When I startup DCS and go into controls.. there is nothing showing for bindings for any aircraft on the Throttle or Stick.

![joypro_export_3 9 6](https://user-images.githubusercontent.com/42323823/128046622-e4ad63c9-0b53-4c19-9a45-66dd66ab432f.png)

![joy_pro_Config X56](https://user-images.githubusercontent.com/42323823/128046922-45f5cc1f-52ff-41cc-9564-98a3464f76a0.png)

**Comment by PJHubbell** [comment]
I think I found out why it was doing it. but not certain it's relevant. I had the boxed checked for "Nuke devices that are untouched by JoyPro". Once i unchecked that, the binds seemed to have exported properly.

**Comment by Holdi601** [comment]
The "nuke devices" box is to create an empty profile for planes and joysticks not covered by your joypro profile. If it works without the checkbox i don't see a reason why it would without it as it just create additional empty profiles in that sense.

**Comment by Holdi601** [comment]
Closing as no more reply came here, if you have further problems please join the discord or open a new thread.
