### ISSUE TITLE
Microsoft VC++ links and others are broken

### ISSUE THREAD

**Issue by KitchenDuty** [Holdi601/JoystickProfiler#27]
can you spell out the entire required packages in your Wiki instead of hard linking them from microsoft so we can google them? or embed them into github as msi's?

**Comment by Holdi601** [comment]
So the only other libraries i am using aside standart .Net 4.7 is the SlimDX.dll in its 64bit version.
The Requirements list is here: https://github.com/JingboYang/slimdx/blob/master/docs/Topics/Deployment%20Guide/Installation.aml 

But to break it down its C++ Redistributables 2010 x64 

> An end user can install the June 2010 DirectX redistributable package, or any later version, and their system will be correctly configured.

Other than that one minor thing is the Shell32.dll from the Windows 10 Installation to ask where your Saved Games Path is.
