### ISSUE TITLE
Crashing upon creating first Add Relations. 

### ISSUE THREAD

**Issue by HighStall** [Holdi601/JoystickProfiler#28]
Creating  'Thrust Both' Relations. selected thrust Query, selected as normal, then removed the one selection 'Corrector' under mi-8mtdesc, or any other selection when trying to de-select, or in other words, removing them from the selection ( UH-1H) Engine RPM 
![JoyPro crash Add Relations](https://user-images.githubusercontent.com/89624319/131071949-de179e41-19ef-4cad-890a-08c194c39456.PNG)

**Comment by Holdi601** [comment]
Hi, so there are 2 crashes within editing relation. One that is triggered within the event trigger of the UI element so the only way i can fix it, by writing my own table UI element.

Workaround so it does not crash: Don't select an instance before exporting. If that keeps unselected it doesn't try to load your local mods, which can cause the Input database go corrupt. 
Another thing is once you checked or unchecked a box in the edit relation window click in the empty field below so it gets submitted. And dont click on checkboxes which have no description.

I will work on a fix once i have time and motivation for it.

**Comment by Holdi601** [comment]
Closing v40 has a new edit relation system which is self build and shouldn't crash anymore. Please test.
