### ISSUE TITLE
JoyPr0 crashes when exporting Binds

### ISSUE THREAD

**Issue by markmit1908** [Holdi601/JoystickProfiler#3]
When exporting any binds the app crashes.

Can load and save profiles.
[DCS_Joypro_1.zip](https://github.com/Holdi601/JoystickProfiler/files/6144273/DCS_Joypro_1.zip)

**Comment by Holdi601** [comment]
Which version and can you upload the exception zip?

**Comment by markmit1908** [comment]
[Exception_132601177325746932.zip](https://github.com/Holdi601/JoystickProfiler/files/6144279/Exception_132601177325746932.zip)

I think it is V0019.  Downloaded a day or so ago.  Not sure where to check.

**Comment by Holdi601** [comment]
Ill upload in an hour or so a new version could you try on that again? and send me the new exception if you get one? As i added a bunch of stuff again :3 thanks

**Comment by markmit1908** [comment]
Thanks. Will do.

**Comment by Holdi601** [comment]
New version is now up. I tested with the profile you provided, but no crash for me. Please keep me updated.

**Comment by markmit1908** [comment]
Thanks! seems to be working again.
