### ISSUE TITLE
Issue Found Manually Assigning A Joystick

### ISSUE THREAD

**Issue by MacIngram** [Holdi601/JoystickProfiler#31]
Tried to assign my joystick to the pitch Relation
Pitch – Manual Input Assignment
I copied the details from the displayed dropdown menu exactly as shown below,

Joystick - HOTAS Warthog (23904C20-7E30-11e9-8002-444553540000)

I then clicked the Add Joystick button
The action was not not permitted and I received the Error Message shown below. However, I cannot see any difference. 

N.B.  I did try to capitalize as per the Error message example, but  this did not work either

Error Message:
Joystick name doesn’t follow needed format: EXAMPLE JOYSTICK (UUIDHERE-6g6g-6g6g-6g6g-000000000000)

**Comment by Holdi601** [comment]
You have to use the right brackets. You are using the normal curved brackets alias ( and ) instead of what you are supposed to use the curly brackets { and }

**Comment by Holdi601** [comment]
![image](https://user-images.githubusercontent.com/18192322/140955796-93ae29bf-8861-4777-8ebb-6072a6a67ad8.png)

**Comment by MacIngram** [comment]
Thanks,
My eyesight even with glasses is terrible, I did not even notice. Doooooh!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Holdi601** [comment]
Alright, have a nice day!

**Comment by MacIngram** [comment]
Hi,
I've seen a number incorrect returns in " Relation"
columns, such as it when entering P51D Flaps down, it also returns "Main bomb switch OFF in Mi-8 column. Do you want a list of those I find?

Regards

TD

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Holdi601** [comment]
What do you mean by incorrect returns?
If you have one hash ID, which is on one aircraft flaps down but on another something else, that is on DCS. That is not an error in my software. Thats how DCS Ids those functions of the Aircraft. But that’s why you have checkboxes to uncheck those unwanted items.
The Ids with the according description are directly imported from DCS exports. Nothing my software does, alteres the Title or ID. It just displays them as they are.

Regards.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Holdi601** [comment]
If you find obvious wrong relations in templates, you can write down, what wrongful relations you find and contact the supplier of the relation file. For instance for Holdi.rl you can tell me in which relation there is illogical stuff. for Chipwich, he is over in the mudspike forums. Denweg is on the discord.
