### ISSUE TITLE
Star Citizen Please

### ISSUE THREAD

**Issue by lazerwolf22** [Holdi601/JoystickProfiler#32]
Star Citizen Please :)

**Comment by Holdi601** [comment]
Its in the works :)

**Comment by Adiventure** [comment]
For curiosities sake, is FS2020 potentially on a to-do list as well?

**Comment by iNgeon** [comment]
Atm still using SCJmapper https://github.com/SCToolsfactory/SCJMapper-V2
Sadly the dev recently abandoned it, would be quite interested. 
I still have a release build but at some stage it might fall apart. It had some great features

**Comment by Holdi601** [comment]
First implementation is there. hence why im closing :)
