### ISSUE TITLE
Crash on relation name filter

### ISSUE THREAD

**Issue by jacrify** [Holdi601/JoystickProfiler#33]
Happens both on previous and latest version. Not sure how to reproduce- maybe related to case? I start typing in relation name filter field, hit tab, and it crashes hard

Love your work, awesome software. 

[Exception_132820071208854033.zip](https://github.com/Holdi601/JoystickProfiler/files/7577336/Exception_132820071208854033.zip)
[Exception_132820094717371823.zip](https://github.com/Holdi601/JoystickProfiler/files/7577337/Exception_132820094717371823.zip)

**Comment by Holdi601** [comment]
will investigate as well

**Comment by Holdi601** [comment]
Fixed with v68

**Comment by jacrify** [comment]
works, thanks!
