### ISSUE TITLE
App crashed on visual assign

### ISSUE THREAD

**Issue by jacrify** [Holdi601/JoystickProfiler#34]
It was working until my layout got to a certain level of complexity. Now it crashes every time I hit visual assign mode
[Exception_132820113119475248.zip](https://github.com/Holdi601/JoystickProfiler/files/7577419/Exception_132820113119475248.zip)
[Joystick Pr0 Stuff.zip](https://github.com/Holdi601/JoystickProfiler/files/7577421/Joystick.Pr0.Stuff.zip)

**Comment by Holdi601** [comment]
will investigate

**Comment by Holdi601** [comment]
Fixed with v68

**Comment by jacrify** [comment]
Awesome, it works! Thanks!
