### ISSUE TITLE
Hind quote escape character

### ISSUE THREAD

**Issue by zbetzen** [Holdi601/JoystickProfiler#36]
Hi, I found an issue with the joystick mapping for the hind that gets created without escape characters for the " marks.

From Joypro You'll get " marks inside the name which breaks the json
		["d3008pnilu3008cd30vd1vpnilvu0"] = {
			["name"] = ""Prepare Weapons" command to gunner",
			["added"] = {
				[1] = {
					["key"] = "JOY_BTN18",
					["JPK"] = "stick index forward",
				},
			},
		},

In DCS you'll get the \\" escape character used within the name field.
		["d3008pnilu3008cd30vd1vpnilvu0"] = {
			["added"] = {
				[1] = {
					["key"] = "JOY_BTN18",
				},
			},
			["name"] = "\\"Prepare Weapons\\" command to gunner",
		},

**Comment by Holdi601** [comment]
A great find! Will fix it in the next release :) Thank you for reporting!

**Comment by Holdi601** [comment]
fixed in next version
