### ISSUE TITLE
Won't link into DCS

### ISSUE THREAD

**Issue by Shamwari** [Holdi601/JoystickProfiler#38]
Hi Guys
This software look fantastic, thanks for your effort developing it!
However after putting all the effort in to allocate each button when I export it to the 'saved games/dcs' it recommended it said it had been successfully uploaded but there is nothing in DCS?
What is wrong and how do I correct this please?

Cheers

**Comment by Shamwari** [comment]
I have looked in my DCS Instance file (as defaulted in JoyPro) and I can't see any of the files I have saved (by pushing 'clear existing binds and export').
Why does nothing seem to be going to the DCS file?

**Comment by Holdi601** [comment]
have you a regular install of DCS or steam, and did you moved the files around on the drive?
And on the bottom where you have to select an instance is it showing up the correct folder?

**Comment by Shamwari** [comment]
﻿
﻿Yes I installed the regular version and didn’t move anything since installing although I asked it to instal on my D drive on the initial install. It put the main folder and game on the d drive but see it has the ‘saved games/DCS’ folder on the c drive. Does this matter?  The automatic instance is correct ( on the c drive as is on my computer}

Thanks for your help

**Comment by Holdi601** [comment]
No as long windows is aware (if you moved your saved games folder) then it is fine. When your Input folder is empty, does it not create any files in the input folder?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Shamwari** [comment]
﻿I have looked at the various aircraft in the input folder and the LUA and JP files are there (each about 4-10KB only in size.

So it looks like they are being sent to the input folder but not being uploaded to DCs from there.

**Comment by Holdi601** [comment]
can you zip your entire input folder and upload it here so i can look into it and test it on my end?

**Comment by Shamwari** [comment]
[Input zip copy.zip](https://github.com/Holdi601/JoystickProfiler/files/7964427/Input.zip.copy.zip)

**Comment by Shamwari** [comment]
Hi Holdi.  Could you open the file?

**Comment by Shamwari** [comment]
It really doesn't make sense to me.  This files seem to be there in config/input/FA18/joystick but when I try to upload them into the controls nothing happens.  I've even re-installed by DCS in case there was an error in the initial install.

I will be very grateful for your advice - I don't know who else to ask.

Cheers

**Comment by Holdi601** [comment]
I havent had time yet, but if you see that it creates thefiles. Could you delete the files or rename the input folder, make a bind from within DCS and check if the file names of joypro created matches the name DCS gives when you make a bind?

**Comment by Holdi601** [comment]
also would it be possible for a more faster exchange for you to join the community discord?

**Comment by Holdi601** [comment]
No replies :c @Shamwari  ?

**Comment by Shamwari** [comment]
Sorry Holdi I have a business meeting now.  I'll get back to you ASAP.

**Comment by Shamwari** [comment]
I deleted the files in the folder.  I am not sure how to save things automatically into this folder from DCS because their controller says save as.. so if I put the same file name then indeed it ends up in the same place but not sure how it works automatically or what it would look like of it did?

**Comment by Holdi601** [comment]
Okay once you deleted inside Saved Games/DCS/Config the "Input" folder inside that, Start DCS go into options > Controls and make assign a key there press OK and close the game. 

Did the folder input reappear?

**Comment by Shamwari** [comment]
Delete the entire folder (not just its contents)?

**Comment by Holdi601** [comment]
Eitherway is fine. It will recreate the folder once you do a bind in the game

**Comment by Shamwari** [comment]
OK, yes that worked - I deleted the entire thing and then on making 1 change in dcs and saying OK, I now have a new Input folder with a F18 subfolder.

**Comment by Holdi601** [comment]
okay can you upload the diff lua here?
And then clean the folder again and then make that bind in joypro export it and paste the diff lua here that it generates in the exact same folder

**Comment by Shamwari** [comment]
There is no diff lua only lua which this site says is not compatible??

**Comment by Holdi601** [comment]
inside the input/FA-18/Joystick should be atleast the diff lua of the key you just bound to your joystick in game

**Comment by Holdi601** [comment]
![image](https://user-images.githubusercontent.com/18192322/153227929-5aba72fc-ab8b-4c5b-b71b-986053b3bd08.png)
 

as an example

**Comment by Shamwari** [comment]
There are lua files for each of my devices (throttle, stick, pedals) which are all lua files. When I drag them to this discussion box there is a long message on the bottom of the box saying 'we don't support that type of file....

**Comment by Shamwari** [comment]
Ive deleted everyting from the input file again and pushed 'clean binds and export on JoyPro and everything seems to have come across from JoyPro properly again.  I'll see what happens when I restart DCS

**Comment by Shamwari** [comment]
OK so there are allocated bindings on DCS controller now.  Is it correct to assume that because I emptied the input folder completely before uploading the JoyPro that these bindings are therefore the JoyPro bindings and not something DCS remembered from my last use?

**Comment by Holdi601** [comment]
Well my assumptions were, that joypro did not had the right saved games folder or the specific binds you are trying to make might be outdated or localized and thus are slightly different.

If the first case would be true, then after deleting your input folder and then bind a key ingame to DCS it created a folder there. After deleting that again and doing the same thing in Joypro the input folder should reappear with content at the exact same place and exact same file names. 

The other option would be to look at the exact same file created and compare the joypro one vs the game created one and compare if the ID for the input is the same highlighted in this screenshot 
![image](https://user-images.githubusercontent.com/18192322/153233611-7aa958f8-4efe-48d4-83de-cf7fa594b71e.png)

Another option is if your joystick has special characters in it, which dcs translates into different buttons then joypro does, then the .diff.lua file have slightly different names


These are the possible error sources here

**Comment by Shamwari** [comment]
Thanks so much.
Let me look into this - it will take a while (I'm no good at this as you have noticed).  I'll tell you if it is all working properly now.

**Comment by Holdi601** [comment]
In case of the first error: make sure to select the right path here:
![image](https://user-images.githubusercontent.com/18192322/153235284-52c9e222-69f3-476b-8637-614a279e4fdb.png)
click on settings and put the DCS saved games path there
![image](https://user-images.githubusercontent.com/18192322/153235441-6885870d-89ab-4862-b664-a98b1b34467e.png)

in the 2nd error case click inside the settings on refresh DCS ID DB watch best this video for how to
https://www.youtube.com/watch?v=r-kyHykQCrs

if the 3rd is the case that the file names differ due to special characters, thats a bug i must fix, but therefor i would need you to tell me to show how it exactly changed

**Comment by Holdi601** [comment]
You got it running shamwari? if no please report back i will close the ticket in a couple days.

**Comment by Shamwari** [comment]
Thanks Holdi

I got it working to some degree which is adequate for me to get on with.

Thanks so much, sorry I didn’t realise you still had a ticket open on this.  I appreciate your help.

Kind regards
Craig

**Comment by Holdi601** [comment]
Alright then Closing the ticket.
