### ISSUE TITLE
Support "Switch" modifier type for DCS

### ISSUE THREAD

**Issue by onufert** [Holdi601/JoystickProfiler#39]
DCS Modifiers Panel has "Modifiers" and "Switches". This boils down to either true/false value for the "switch" field in the modifiers.lua file. 

It would be great if JoyPro was able to add some kind of IsSwitch field to its Modifiers creation page that would set this value correctly in the generated modifiers.lua file.

Work around right now is after I export clean, I manually go in and edit the modifiers.lua file for each aircraft and set the switch key to true. 

```
	["JOY_BTN57"] = {
		["device"] = "LEFT VPC Throttle MT-50CM3",
		["key"] = "JOY_BTN57",
		["JPK"] = "JOY_BTN57",
		["switch"] = true,
	},
```

**Comment by Holdi601** [comment]
I see, I ll work on it once i have time.

**Comment by Holdi601** [comment]
Should be in v70 once it releases. Once its there please test if it works properly.
