### ISSUE TITLE
Joystick recognized incorrectly

### ISSUE THREAD

**Issue by brp51d** [Holdi601/JoystickProfiler#4]
I installed  joypro to set up DCS controls.

I researched joypro and installed it. After backing up my DCS input file, I started creating a profile.

The problem is that when I set up axis for pitch , roll and rudder, joypro reads pitch and roll as joy z and rudder as joy x

My joystick is a ch products fighterstick, rudder is ch pro pedals. Both are calibrated and function and are recognized correctly in all flight Sims including the control mapping inside DCS world.

The program looks great and I must be missing something obvious.

Any help is appreciated.

**Comment by Holdi601** [comment]
Hmm Im not sure if the threshhold might be just too low or wrong, or if it really messes up the axis. Is it constantly exchanging 2 axis with each other ? and how is it looking the "joy.cpl" control panel? For quicker communication feel free to join the discord :)

**Comment by brp51d** [comment]
I was able to fix this problem. My joystick axis must have some noise but eventually it read the correct axis

I created a profile but I'm not sure which box at the bottom I should use to save it.

I want to overwrite the settings I created without erasing other settings that are plane specific in DCS.

I was going to click the middle box at the bottom of the page but I am unsure.

I have tried to join the discord but it keeps telling me the invitation expired.

thanks again for your help.

**Comment by Holdi601** [comment]
Try this link https://discord.gg/SeCTXJHhJf im gonna change everywhere to this link

**Comment by Holdi601** [comment]
Also i have added a new build which lets you tweak some settings in regards to axis and button detection. Feel warmly invited to join the discord :)

**Comment by brp51d** [comment]
thank you!

**Comment by brp51d** [comment]
When I click on the link, the page says unable to accept

**Comment by Holdi601** [comment]
Mhh let me check

**Comment by Holdi601** [comment]
pick any of the codes for discord they should all work if not put them manually in disc.
![image](https://user-images.githubusercontent.com/18192322/111831615-ed9d4380-88ef-11eb-8878-bd5e6ca5a9ad.png)

**Comment by Holdi601** [comment]
If not give me your username, im gonna add you and manually invite you.
