### ISSUE TITLE
Grim Reapers X-56 Profiles

### ISSUE THREAD

**Issue by incryptx** [Holdi601/JoystickProfiler#40]
More of a suggestion, as opposed to an issue.

Grim Reaper built X-56 Profiles for all of the aircraft in DCS. Problem is, you have to import each profile individually and manually into each aircraft type, which is a PITA.

Although your application takes a somewhat different approach, adding the same profile to all aircraft, it would be nice to have a secondary function to take the grim reaper profiles for each aircraft and import them into each aircraft type, as opposed to doing all of that manually.

Just a thought.

**Comment by incryptx** [comment]
This would be only for the X-56 and only using Grim Reaper's X-56 Profiles for all aircraft. It would be a secondary/optional function, as your main goal is just to import/add one profile to all aircraft for any controller.

**Comment by Holdi601** [comment]
No you dont need to import each aircraft one by one. I already imported once all x52 binds from the gream reapers a couple months back and put it in the template folder.  
I can redo it so the relation names are better. But for quickly assigning the x56 according to the reapers style should not take you long

**Comment by incryptx** [comment]
You misunderstand. To use GR's profiles alone, without your software, you need to import them one by one. That was my meaning. If I understand you, you did your X52 imports of GR's x52 profiles all at once putting it into a template folder?

Then all we (your users) should need from you is the relation names and your template folder?

In conclusion, it seems easier for users to import pre-written profiles as apposed to building relations or using one profile for all aircraft.

I applaud your beta joypro software as the number one complaint from DCS users has always been manually building profiles for each aircraft. As for the novice crowd, most find it difficult at best and impossible for most.

**Comment by Holdi601** [comment]
I will rework the GR pr0file once i have done some other things.

**Comment by incryptx** [comment]
Thanks. It’s appreciated.
