### ISSUE TITLE
Modifiers and switches

### ISSUE THREAD

**Issue by YMA2020** [Holdi601/JoystickProfiler#41]
Hello,
Thanks for the great work.
I noticed two issues (probably interconnected) that need a fix:
1- If a modifier is added, it does not get transferred to DCS 
2- If a modifier is added and marked as a switch, the switch flag does not persist upon reopening the same relation/profile files

Thanks again

**Comment by Holdi601** [comment]
The modifier gets only exported to those aircraft for which you use the modifier. Its not getting exported to all, in case you dont want it on some aircraft.
Number 2 ill look into it

**Comment by Holdi601** [comment]
Fixed for next version

**Comment by YMA2020** [comment]
Many thanks.
For number 1, I think it works only if the modifier and the button binding are on the same device.
If the modifier is on one device and the button binding is on a different one, the modified button binding is not exported
For example, I have a switch on the throttle that acts as mode modifier and when it is on some buttons on the stick should do different function.

**Comment by Holdi601** [comment]
yes yes but i saw it and have a fix already but i want to finish up 3 other features before i release v73 which has the fix for it

**Comment by Holdi601** [comment]
@YMA2020 version is now online please test. if issue still persist please report :)
