### ISSUE TITLE
Joystick Profiler Relations Are Unable to Recognise Virpil Control Panels 1, 2 and SHARKA 50

### ISSUE THREAD

**Issue by atom1964** [Holdi601/JoystickProfiler#42]
Hi Guys,
Using this great piece of software to create and link bindings to my DCS software. It recognises my VIRPIL joystick, throttle and rudder pedal units, but will not recognise my 3 VIRPIL Control Panels (1, 2 and SHARKA 50).

I am using the latest 'Holdi.rl' file to load pre-set 'Relations' as a base template. When selecting 'Device Filter' on the main screen it only shows (and ticks) the following, as being recognised by JoyPro:-
Unassigned
VPC Joystick
VPC Throttle
VPC Pedals.
**There is no mention of the VPC Controls Panels 1, 2 and Sharka 50 in this list, even though they have been fully configured (all buttons and sliders configured correctly) with the latest firmware in the VPC Configuration Program. 
I also noticed that DCS also does NOT recognise these three panels. Why is this and what do I need to do for DCS to recognise these three panels? Do I also need to use VJOY for DCS to be able recognise them?**

What is causing this problem and what do I need to do to resolve this issue? At the moment I cannot even manually create the bindings in DCS for all my 20+ planes for these three VPC Control Panels. I want to stay clear of having to configure manually in DCS as I know it will be a horrendous and ongoing tasks, as the various bits of software (including windows updates) change over time. 

I noticed that the Holdi.rl file shows picture of the VPC Control panels 1 and 2, so it's for that very reason I used this new template file to load my Relations in to VJoy. But without success. Is this because DCS is currently not recognising the three control panels? I think so!

**I also noticed that when I have loaded the Holdi.rl template and then trying to ADD a new Relation to it, nothing happens, and all the other buttons then stop working, although you can still scroll up and down through the list of existing relations.**

Is anyone able to please help me quickly in my predicament? Any assistance in the above two problems will be greatly appreciated, as I cannot proceed forward at present in JoyPro.
Many thanks!

**Comment by Holdi601** [comment]
If you open the windows Joy.cpl control panel do you see your devices listed there?

as a last fallback you can also manually assign and create sticks by joystick as you can see here https://youtu.be/4zMcYzhgv7E?t=127 or use the visual assigning mode.

Joypro uses a library called SlimDX for getting all joystick inputs. It is basically a light weight DirectX 11 interface to query what DirectInput devices are there. If they are not listed DirectX does not see them. However i have heard from other VPC customers that you can tail the control panels to the throttle maybe you have done that?

**Comment by Holdi601** [comment]
Also for more reactive and fast trouble shooting we can go into discord and discuss it there if you need a solution asap

**Comment by Holdi601** [comment]
Also inside DCS are your VPC panels listed as their own devices?
If they are functioning internally as Keyboards then they won't work as Joypro currently does not support Keyboards and only DirectInput devices such as technically any gamepad or other joystick esc device, which i would believe is the case for the VPC panels, but i only have 2 VPC sticks and throttle and they seem to work without a problem. Also on our discord is one user who also uses the VPC control panels and he seems to got it working.

**Comment by atom1964** [comment]
Thank you for your quick response! Much appreciated!

First question is how do I get onto your discord please? Is there a URL link that you could provide that will direct me straight there?

If I open the device window in JoyPro.cpl control panel (which I presume is the home screen) then all I see are the following:-

Unassigned
VPC Joystick
VPC Throttle
VPC Pedals.

I notice that **none** of the three VPC Control panels I have configured in VPC are listed in DCS, which leads me to think that is the root cause of the problem I'm facing, as the other three VPC devices I also have (Joystick, throttle and rudder pedals) are listed directly in DCS. Therefore I need a solution to get DCS to recognise my three VPC control panels in addition to the other three VPC devices it already has identified. Would creating logical devices in VJoy be a solution? I don't want to spend lots of time with VJoy if that does not work easily with JoyPro. 
My version of my VPC joystick and throttle units does not allow me to tail/link a single control panel to either the throttle or joystick, as otherwise I would have done that. Therefore they are all installed in standalone mode.

**I also noticed that when I have loaded the Holdi.rl template and then trying to ADD a new Relation to it, nothing happens, and all the other buttons then stop working, although you can still scroll up and down through the list of existing relations.**

Any help you can give me to quickly get me restarted would be extremely appreciated.
Many thanks!

**Comment by Holdi601** [comment]
https://discord.gg/yK4gQA9xgk is the discord

No i mean with joy.cpl this thing
![image](https://user-images.githubusercontent.com/18192322/158070225-6f18449b-beea-4660-81ed-ab81843c1a52.png)

One person on the discord came back having also the control panels and they said they have no issues.

**Comment by Holdi601** [comment]
I would highly advise talking with someone of the 2 people on our discord how they configured their control panels

**Comment by atom1964** [comment]
No VJoy device under Game Controller on my systemas I had already uninstalled VJoy before installing JoyPro.  All I have listed under Game Controller on my PC are my Joystick, Throttle and Rudder Pedals; nothing more.

Thanks for the link to discord site.

Do you have any further information why I cannot add a new Relation if I'm already using your Relation Template 'Holdi.rl'?

Many thanks!

**Comment by denwagg097** [comment]
I have CP1 and CP2 no problems. If you cannot see them in joy.cpl there is a problem with you VPC configuration.
After you make changes you must always save your profile, calibrate if needed and click the save VPC  device to write it to the device
![11](https://user-images.githubusercontent.com/101524495/158075539-68e92eaa-b372-4fa0-b9dc-c0037c470a4d.jpg)
 
another thing do not slave them to another VPC device unless you know what you are doing if you do then you will not see the device that is slaved
set it up like this 
![22](https://user-images.githubusercontent.com/101524495/158075618-92f22fa9-69ec-465b-ba8c-cfa10e4e28d3.jpg)

**Comment by atom1964** [comment]
Hi,
Thank you for your response. I will reconfigure them again in VPC as stand alone panels and will then check my Games Controller utility on my PC to see that they are there. Hopefully that should resolve it. After which I will load JoyPro vers. 73, so I have the latest and start again with the Holdi.rf file as a base template.
Thanks again for your help. Will let you know the outcome!

**Comment by Holdi601** [comment]
You got it running atom? if no please report back i will close the ticket in a couple days.

**Comment by atom1964** [comment]
Hi 
I’ve got it running! many thanks for your support on this! I had configured the control panels as ’Slave’, whereas i should have configured it for ‘Joystick (USB)’. It now workson my PC, as the Game Controller has now recognised all my Virpil devices, so JoyPro should as well.
Waiting for Version 74 to be released before I load JotPro to my PC and start configuring DCS World.

What is the recommended process for updating from, say, version 73 to &4. Does one have to back-up all the configuration first (that would be necessary irrespective of the process used) and then delete the old program and it’s directories, before installing the new version? Or can one just install the new version (after config back-up) and it will automatically identify the previous version and overwrite what is necessary? Please advise on the process for this.

Many thanks!

**Comment by Holdi601** [comment]
You should be able to update without problem. The only issues you might have is when you have quaggles commands which are not in my default DCS DBs, then you need to refresh the DCS DB. 
https://www.youtube.com/watch?v=r-kyHykQCrs

or the wiki entry about it:
https://github.com/Holdi601/JoystickProfiler/wiki/Database

**Comment by atom1964** [comment]
Many thanks! Will look at this tomorrow now!

**Comment by Holdi601** [comment]
Closing the ticket.

**Comment by atom1964** [comment]
Please close ticket!
Thanks!
