### ISSUE TITLE
cannot finish updating

### ISSUE THREAD

**Issue by jinchoung** [Holdi601/JoystickProfiler#47]
whenever i launch joypro now, it tells me there's a new version and would i like to update. and i say yes. but then it ends up downloading "NewerVersion.zip" which is actually corrupt or not otherwise recognized as a zip file. then it gives me one last chance to not update but when i tell it to update anyway, it brings up a console where some things happen quickly but too quickly for me to see... it looks like it did something tho.

but upon re-launch joypro, it goes right back to telling me a new version exists and whether i would like to update.

i wouldn't mind manually updating - should i just overwrite the existing files and folders with the new ones?

thanks!

**Comment by deejaylg** [comment]
same bug at my end, "NewerVersion.zip" is corrupt 196 KB.
you can grab it from github, extract the archive to joypro folder, an overwrite old files,
or replace the corrupted NewerVersion.zip with the corrrect one in joypro folder, restart&let the app to do the magic for you ;)

**Comment by Holdi601** [comment]
check newest version
