### ISSUE TITLE
impossible to find the rigth folder 

### ISSUE THREAD

**Issue by partoll** [Holdi601/JoystickProfiler#48]
During the first launch, JSP didn't start : 

He try to find K disk, but i didn't have it rigth now, i have one during the re-instalation of the new windows, then i renomate the new and the K:  became D:  after remove the old windows.  i try with one USB drive with letter as K, and empty folder user\saved games , then it's working. Means he find somewhere the initial letter, but not the actual windows folder D:\user\Saved Games.   then in my installation DCS are in the D:\users\documents\My Games.  means we need the opportunity to give to him the right address. 

System.Windows.Threading.DispatcherUnhandledExceptionEventArgs
#
'L'invocation du constructeur sur le type 'JoyPro.MainWindow' qui correspond aux contraintes de liaison spécifiées a levé une exception.' numéro de ligne '6' et position de ligne '9'.
#
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
#
System.Collections.ListDictionaryInternal
#
_**### Impossible de trouver une partie du chemin d'accès 'K:\pauto\Saved Games'.**_
#
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.Directory.GetDirectories(String path)
   à JoyPro.InitGames.GetDCSUserFolders() dans D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\DataStructures\InitGames.cs:ligne 161
   à JoyPro.MainStructure.InitProgram() dans D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\General\MainStructure.cs:ligne 317
   à JoyPro.MainWindow.FirstStart() dans D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\Windows\MainWindow.xaml.cs:ligne 2609
   à JoyPro.MainWindow..ctor() dans D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\Windows\MainWindow.xaml.cs:ligne 93
#
System.Collections.ListDictionaryInternal

**Comment by Holdi601** [comment]
Joypro asks your windows system where your saved game folder is. Check your registry for key "4C5C32FF-BB9D-43B0-B5B4-2D72E54EAAA4" as that is the saved games folder as you can see here:
![image](https://user-images.githubusercontent.com/18192322/194041976-a84b536e-6dd2-4750-a510-1e1ed6a09991.png)

otherwise if joypro intermediate data ever becomes a problem in your Documents/JoyPro/meta.info has some intermediate info you can delete to reset to joypro acting like a first start

**Comment by partoll** [comment]
Hello Holdi601,

Thank a lot,  in fact, i find out around 20 wrong entry in my registry, i make a cherch with K:\  and modif all of them by D:\ (not only saved games)  , then JoyPro work perfectly.

Thank a lot for your help.
