### ISSUE TITLE
JoyPro loading

### ISSUE THREAD

**Issue by Nicol2106** [Holdi601/JoystickProfiler#49]
Application is loading cca 2,5 minutes before app window pops up. Tested on W11 and W10

**Comment by Holdi601** [comment]
If you plan to not use Joypro with your keyboard at all, you can delete the content of JoyPro\KeyboardCleanProfile\DCS\* that speeds it up by a lot. Some people have really long loading times for that for some reason.

**Comment by Holdi601** [comment]
v84 will have a startup parameter if you want to launch it without keyboard stuff

**Comment by Holdi601** [comment]
-nokeyboard argument is added
