### ISSUE TITLE
joyPro V30 Crashing

### ISSUE THREAD

**Issue by PJHubbell** [Holdi601/JoystickProfiler#5]
I am using the latest build v30. I ensure all the previous Keybinds were backed up and cleared in DCS open Beta . Launch the app, as soon as I choose the game from dropdown.. it crashes. All other buttons are greyed out exceipt exchange device and settings. Error attached with logs

[Exception_132614540047229368.zip](https://github.com/Holdi601/JoystickProfiler/files/6222174/Exception_132614540047229368.zip)
![JoyProv30_Crash](https://user-images.githubusercontent.com/42323823/112847341-9a07c400-906c-11eb-9f5b-5746d503d36e.jpg)

**Comment by Holdi601** [comment]
Thanks! Will look into it!

**Comment by Holdi601** [comment]
Found the issue, fix will be in v31 please use the old version in the meantime :)

**Comment by Holdi601** [comment]
Closing as v31 is published. Please reopen if other issues come up.
