### ISSUE TITLE
Windows does not appear when launch the exe

### ISSUE THREAD

**Issue by itrowa** [Holdi601/JoystickProfiler#50]
Version: JoyPro_Winx64_v0084.zip
OS: Windows 10 64 bit 
all Requirements are installed.

but when launch JoyPro.exe no window appears, I can find the JoyPro runs in windows task manager.

**Comment by heyewong** [comment]
it looks like the windows finally appears after waiting for serval minutes!

**Comment by Holdi601** [comment]
yeah the parser i wrote for any lua data is really not the fastest and then when it has to go through hundreds of lua files especially keyboard on a slow drive it can take some time. If you are not planning to map out your keyboard with joypro you can fasten up by significantly putting it on a fast SSD and or start joypro with the argument -nokeyboard
