### ISSUE TITLE
v0084 - Unhandled Exception Error When Launching JoyPro

### ISSUE THREAD

**Issue by DetMafia** [Holdi601/JoystickProfiler#53]
JoyPro successfully launched the first time after I downloaded. I immediately closed out of the app as I didn't have time to set key binds at that time > (and planned to return later).

The second time I tried launching JoyPro, the app never opened.
I tried a couple more times, rebooted, re-launched DCS, etc. But I've not been able to get JoyPro to open/run.

- I checked the Event Logs and found each attempt to execute JoyPro throws the same Unhandled Exception errors:
- Event ID 1026 - .NET Runtime (source)
- Event ID 1000 - Application Error

I've attached the Event Logs for review.
Please Help!
[JoyPro_Crash_Report.zip](https://github.com/Holdi601/JoystickProfiler/files/10039134/JoyPro_Crash_Report.zip)

**Comment by Holdi601** [comment]
Can you send me the unhandeled exceptions from the Joypro folder pls?

**Comment by DetMafia** [comment]
@Holdi601 > Update on tasks performed:
Per the event logs, there appeared file corruption may be at play, so I ran the following commands. SFC did find and successfully repair corrupted files > but it didn't resolve the problem.

- DISM.exe /Online /Cleanup-image /Restorehealth
- Then ran: sfc /scannow
(Attached the CBS log for reference too)

I then tried rolling back to a Restore Point to a date before downloading/running JoyPro.
Ran DISM & SFC commands again (no corruption found the 2nd time).
Re-downloaded JoyPro & extracted to a different location.

- Was prompted (like the first time) to "Allow"
- But it immediately threw the same exception.


[JoyProExceptions.zip](https://github.com/Holdi601/JoystickProfiler/files/10047705/JoyProExceptions.zip)
[CBS.zip](https://github.com/Holdi601/JoystickProfiler/files/10047709/CBS.zip)

**Comment by DetMafia** [comment]
@Holdi601 > I decided to just rebuild my whole rig.

- Installed/Updated: Steam/SteamVR, HTC Pro software/drivers, HOTAS app & drivers, RTX3090 drivers, etc. (you know...everything)!
- Reinstalled DCS, launched & made tweaks to System settings, etc.
- Flew a couple "Free Flights".

I re-downloaded JoyPro_v0084 & extracted to C:\Game_Folders\JoyPro

I launched from same location (C:\Game_Folders\JoyPro) > No problems

- This time I took time to Load Relations, make some edits (Pitch, Roll, Throttle, etc.) & saved the profile.
- Exported the binding (successful).
- Validated all of the models populated the location: C:\Users\zzzzz\Saved Games\DCS\Config\Input
- Exited JoyPro & ran DCS: Successful

I quit DCS & tried to open JoyPro > Same exact Unhandled Exception was thrown.

- Again, I'm unable to re-open JoyPro.

2 new items I tried for troubleshooting:

1. Deleted meta.info

- Reason: Per your YouTube channel video (#14 JoyPro doesn't start anymore: https://www.youtube.com/watch?v=EM1Ou2USzL0&list=PLlzaQN7UpUfh3b98GOSMe3LHgXxLziFca&index=14   ) > Remove file (meta.info) to clear the state of the window when JoyPro was last open.
This didn't help unfortunately.

2. So, I tried changing the DPI scaling of JoyPro to "System" as the buttons & layout are quite large on my monitor. (Note: I connect to an LG OLED65CX and some apps just need this changed > even my X56 HOTAS app needs this changed just to navigate the app).  And also repeated removal of meta.info > but the results were still the same.

Let me know next steps.
Thanks

**Comment by DetMafia** [comment]
Related info in the log: [11/21/2022 5:32:12 AM]: 	The invocation of the constructor on type 'JoyPro.MainWindow' that matches the specified binding constraints threw an exception.

- So there may be some sort of relation to the app window?

[log.zip](https://github.com/Holdi601/JoystickProfiler/files/10053739/log.zip)

**Comment by Holdi601** [comment]
I started yesterday implementing a proper fix when im back from work today i will look more into it.


Von Outlook<http://aka.ms/weboutlook> gesendet.

________________________________
Von: DetMafia ***@***.***>
Gesendet: Montag, 21. November 2022 06:40
An: Holdi601/JoystickProfiler ***@***.***>
Cc: Holdi601 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Holdi601/JoystickProfiler] v0084 - Unhandled Exception Error When Launching JoyPro (Issue #53)


Related info in the log: [11/21/2022 5:32:12 AM]: The invocation of the constructor on type 'JoyPro.MainWindow' that matches the specified binding constraints threw an exception.

  *   So there may be some sort of relation to the app window?

log.zip<https://github.com/Holdi601/JoystickProfiler/files/10053739/log.zip>

**Comment by Holdi601** [comment]
v85 released and has a fix

**Comment by DetMafia** [comment]
Confirmed > issue has been resolved.
