### ISSUE TITLE
Modifier dropdown functionality

### ISSUE THREAD

**Issue by tijmenvn** [Holdi601/JoystickProfiler#55]
When not exactly clicking the checkbox inside the modifier dropdown list. The modifier is not selected.

However, The modifier text is displayed now. Implying this relation is using the selected modifier when in reality it isn't when opening the dropdown again

I would recommend changing the dropdown behavior so users can simply click on the text inside the dropdown window and not specifically the checkbox

**Comment by Holdi601** [comment]
fixed for next release
