### ISSUE TITLE
Question on versions of DCS

### ISSUE THREAD

**Issue by fancnc** [Holdi601/JoystickProfiler#7]
I am running 2.5 DCS open Beta

When I run Joypro and select "Clean Existing Binds and Export"  It seems it is not working.  

 I run JoyPro and select "Clean Existing Binds and Export"  I no longer get the popup box saying the job is complete. I have waited over 5 minutes to see if I do get the notice.

When I check a number of aircraft,  I still see the setting DCS configures.  DCS has a habit of configureing all kinds of invalid setting to my Virpil rudder pedals. After running JoyPro and selecting Clean existing binds and export the DCS binds are still in effect, 

Any suggesting on what I am doing wrong.  I'm thinking it is my problem as no one else has reported what I am experencing. 
Tks 
George

**Comment by Holdi601** [comment]
With the New version, as upon user request, it asks you if you really want to export. If you click no or X then it wont export.
 You have to click yes. You can try v31 as that one doesn't have the confirmation question, and thats the only thing that changed from 31 to 32. Aside from sorting and a minor name change.  
 If you do that already, try to delete the c:\user\YOU\documents\JoyPro folder as it saves meta data there, delete that and see if it works again. If it still persists, try and make a video of the issue.

**Comment by fancnc** [comment]
Movie is on youtube.  I tried it with V31 with same results. 
Tried 7zip.  Uploaded it to Google Drive
Use   JoyPro  for access

https://drive.google.com/file/d/1ZnX0C9wvDEV3nRi8AaZdqk6Vmn2NXKqy/view?usp=sharing

**Comment by Holdi601** [comment]
I dont have access to that file.

**Comment by Holdi601** [comment]
One thing for you to check, when on clicking on export no message would come, if no instance Path is selected or when one is selected, when it tries to export it doesn't exist anymore or cant read or write to it.

**Comment by Holdi601** [comment]
Closing as solution discussed and went live with v0033.
