### ISSUE TITLE
Exchange Stick Error?

### ISSUE THREAD

**Issue by teslabolt77** [Holdi601/JoystickProfiler#9]
If I select either of these options, the program crashes. Any ideas? 

I have also noticed several versions of HOTAS that I am not sure are related to the problem. Where does it source the HOTA info from?

![Screenshot 2021-04-20 204339](https://user-images.githubusercontent.com/82906717/115484837-1c714700-a219-11eb-851e-54ced29c43e2.png)

![Screenshot 2021-04-20 204344](https://user-images.githubusercontent.com/82906717/115484841-1c714700-a219-11eb-908a-92fda11b634d.png)

![Screenshot 2021-04-20 204603](https://user-images.githubusercontent.com/82906717/115485089-a3beba80-a219-11eb-9b7d-84430f30f25e.png)

**Comment by teslabol77** [comment]
![Screenshot 2021-04-20 204603](https://user-images.githubusercontent.com/82906717/115485062-99042580-a219-11eb-9316-5e7214d6499e.png)

**Comment by Holdi601** [comment]
Can you upload the Exception.zip within the folder that it creates?

**Comment by teslabolt77** [comment]
Sure thing.

[Exception_132634431047889992.zip](https://github.com/Holdi601/JoystickProfiler/files/6368907/Exception_132634431047889992.zip)

**Comment by Holdi601** [comment]
I have a crash fix, in the next version, but the error seems odd to me, once the next version is life check back please if everything works :3 thanks if further bugs appear, Ill fix em.

to your earlier question. The import window checks your DCS instances folder for sticks that existed once upon a time there and lists them there. 

In the exchange stick Window it asks the directX11 api for connected gamepad devices and lists them there.

**Comment by Holdi601** [comment]
V36 is up with crash frix. If issue still persist, please make another ticket or come discord :) Hope everything checks out for you. /closing
